//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trainees.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFMSurvey
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Type { get; set; }
        public string Language { get; set; }
        public Nullable<int> Responses { get; set; }
    
        public virtual CFMUser CFMUser { get; set; }
        public virtual CFMUser CFMUser1 { get; set; }
    }
}
